apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops
  name: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
  strategy: {}
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - image: sahan93/test-devops:3
        name: devops
        resources: {}
