apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops
  name: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
  strategy: { }
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - image: sahan93/test-devops:5
          name: devops
          resources: { }
          env:
            - name: CONFIG_MAP_VALUE
              valueFrom:
                configMapKeyRef:
                  key: my_config_map_key
                  name: test-devops
        - image: docker.elastic.co/logstash/logstash:8.6.1
          name: logstash
          ports:
            - containerPort: 5044
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-config
          resources: { }
      volumes:
        - name: logstash-config
          configMap:
            name: logstash