apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops
  name: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
  strategy: {}
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - image: sahan93/test-devops:4
        name: devops
        resources: {}
        env:
          - name: CONFIG_MAP_VALUE
            valueFrom:
              configMapKeyRef:
                key: my_config_map_key
                name: test-devops
