apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: devops
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          service:
            name: devops
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
