apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops
  name: devops
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 5044-5044
      port: 5044
      protocol: TCP
      targetPort: 5044
  selector:
    app: devops
  type: ClusterIP
