apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops
  name: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
  strategy: { }
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - image: sahan93/test-devops:latest
          name: devops
          resources: { }
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: db_url
                  name: test-devops
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: db_username
                  name: test-devops
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: db_password
                  name: test-devops
            - name: CONFIG_MAP_VALUE
              valueFrom:
                configMapKeyRef:
                  key: my_config_map_key
                  name: test-devops
